### ISSUE TITLE
Api access?

### ISSUE THREAD

**Issue by vinnyt** [dvhx/what-can-i-build#1]
Would there be a way to create an api from this?

**Comment by dvhx** [comment]
I don't think so (in a sense that you call url and gives you result) because this runs entirely on client. I made it this way to avoid needing full server and to make it work on github pages (it's basically static website). You can include all circuits in single file:

```
<script src="https://dvhx.github.io/what-can-i-build/circuit/circuits.js"></script>
<script>
console.log('There are ' + Object.keys(SC.circuit).length + ' circuits');
console.log('Fuzz face uses ' + Object.keys(SC.circuit['fuzz_face'].parts).length + ' parts');
</script>
```
In console it would print:

```
There are 287 circuits
Fuzz face uses 12 parts
```
You can then make any function you want (e.g. parts search, notifying on new circuits, whatever...)

**Comment by vinnyt** [comment]
Ok that’s makes sense thanks for the reply
